- project:
      name: deploy-menlo-tost-staging
      rancher_cluster: "ace-menlo"
      k8s_config: "k8s-menlo-tost-staging"
      terraform_dir: "staging/ace-menlo"
      rancher_api: "rancher_staging_terraform_access"
      jobs:
          - "deploy"
          - "deploy-shared"
          - "deploy-onos"
          - "deploy-stratum"
          - "deploy-telegraf"
- project:
      name: deploy-menlo-tost-dev
      rancher_cluster: "tost-dev"
      k8s_config: "k8s-menlo-tost-dev"
      terraform_dir: "testing/menlo-tost"
      rancher_api: "rancher_dev_terraform_access"
      jobs:
          - "deploy"
          - "deploy-shared"
          - "deploy-onos"
          - "deploy-stratum"
          - "deploy-telegraf"
- project:
      name: deploy-menlo-production
      rancher_cluster: "ace-menlo"
      k8s_config: "k8s-menlo-tost-prod"
      terraform_dir: "production/ace-menlo"
      rancher_api: "rancher_prod_terraform_access"
      jobs:
          - "deploy"
          - "deploy-shared"
          - "deploy-onos"
          - "deploy-stratum"
          - "deploy-telegraf"
